# Generated by Django 6.0.4 on 2026-04-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='contacts/', verbose_name='Иконка (Image)')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Заголовок (UZ)')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок (RU)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Заголовок (EN)')),
                ('desc_uz', models.TextField(verbose_name='Описание (UZ)')),
                ('desc_ru', models.TextField(verbose_name='Описание (RU)')),
                ('desc_en', models.TextField(verbose_name='Описание (EN)')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('details', models.TextField(blank=True, verbose_name='Детали')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='ExperienceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Заголовок (UZ)')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок (RU)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Заголовок (EN)')),
                ('desc_uz', models.TextField(verbose_name='Описание (UZ)')),
                ('desc_ru', models.TextField(verbose_name='Описание (RU)')),
                ('desc_en', models.TextField(verbose_name='Описание (EN)')),
            ],
            options={
                'verbose_name': 'Карточка Experience',
                'verbose_name_plural': 'Карточки Experience',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Картинка (Image)')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Заголовок (UZ)')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок (RU)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Заголовок (EN)')),
                ('desc_uz', models.TextField(blank=True, verbose_name='Описание (UZ)')),
                ('desc_ru', models.TextField(blank=True, verbose_name='Описание (RU)')),
                ('desc_en', models.TextField(blank=True, verbose_name='Описание (EN)')),
            ],
            options={
                'verbose_name': 'Карточка Галереи',
                'verbose_name_plural': 'Карточки Галереи',
            },
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='services/', verbose_name='Иконка (Image)')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Заголовок (UZ)')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок (RU)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Заголовок (EN)')),
                ('desc_uz', models.TextField(verbose_name='Описание (UZ)')),
                ('desc_ru', models.TextField(verbose_name='Описание (RU)')),
                ('desc_en', models.TextField(verbose_name='Описание (EN)')),
            ],
            options={
                'verbose_name': 'Карточка Услуги',
                'verbose_name_plural': 'Карточки Услуг',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Логотип Navbar')),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Логотип Footer')),
                ('tg_bot_token', models.CharField(blank=True, max_length=255, verbose_name='Telegram Bot Token')),
                ('tg_chat_id', models.CharField(blank=True, max_length=255, verbose_name='Telegram Chat ID')),
                ('hero_mini_title_uz', models.CharField(blank=True, max_length=255, verbose_name='Hero Mini Title (UZ)')),
                ('hero_mini_title_ru', models.CharField(blank=True, max_length=255, verbose_name='Hero Mini Title (RU)')),
                ('hero_mini_title_en', models.CharField(blank=True, max_length=255, verbose_name='Hero Mini Title (EN)')),
                ('hero_title_uz', models.TextField(blank=True, verbose_name='Hero Title (UZ)')),
                ('hero_title_ru', models.TextField(blank=True, verbose_name='Hero Title (RU)')),
                ('hero_title_en', models.TextField(blank=True, verbose_name='Hero Title (EN)')),
                ('hero_desc_uz', models.TextField(blank=True, verbose_name='Hero Desc (UZ)')),
                ('hero_desc_ru', models.TextField(blank=True, verbose_name='Hero Desc (RU)')),
                ('hero_desc_en', models.TextField(blank=True, verbose_name='Hero Desc (EN)')),
                ('exp_mini_title_uz', models.CharField(blank=True, max_length=255, verbose_name='Exp Mini Title (UZ)')),
                ('exp_mini_title_ru', models.CharField(blank=True, max_length=255, verbose_name='Exp Mini Title (RU)')),
                ('exp_mini_title_en', models.CharField(blank=True, max_length=255, verbose_name='Exp Mini Title (EN)')),
                ('exp_title_uz', models.TextField(blank=True, verbose_name='Exp Title (UZ)')),
                ('exp_title_ru', models.TextField(blank=True, verbose_name='Exp Title (RU)')),
                ('exp_title_en', models.TextField(blank=True, verbose_name='Exp Title (EN)')),
                ('exp_desc_uz', models.TextField(blank=True, verbose_name='Exp Desc (UZ)')),
                ('exp_desc_ru', models.TextField(blank=True, verbose_name='Exp Desc (RU)')),
                ('exp_desc_en', models.TextField(blank=True, verbose_name='Exp Desc (EN)')),
                ('service_mini_title_uz', models.CharField(blank=True, max_length=255, verbose_name='Service Mini Title (UZ)')),
                ('service_mini_title_ru', models.CharField(blank=True, max_length=255, verbose_name='Service Mini Title (RU)')),
                ('service_mini_title_en', models.CharField(blank=True, max_length=255, verbose_name='Service Mini Title (EN)')),
                ('service_title_uz', models.TextField(blank=True, verbose_name='Service Title (UZ)')),
                ('service_title_ru', models.TextField(blank=True, verbose_name='Service Title (RU)')),
                ('service_title_en', models.TextField(blank=True, verbose_name='Service Title (EN)')),
                ('service_desc_uz', models.TextField(blank=True, verbose_name='Service Desc (UZ)')),
                ('service_desc_ru', models.TextField(blank=True, verbose_name='Service Desc (RU)')),
                ('service_desc_en', models.TextField(blank=True, verbose_name='Service Desc (EN)')),
                ('gallery_mini_title_uz', models.CharField(blank=True, max_length=255, verbose_name='Gallery Mini Title (UZ)')),
                ('gallery_mini_title_ru', models.CharField(blank=True, max_length=255, verbose_name='Gallery Mini Title (RU)')),
                ('gallery_mini_title_en', models.CharField(blank=True, max_length=255, verbose_name='Gallery Mini Title (EN)')),
                ('gallery_title_uz', models.TextField(blank=True, verbose_name='Gallery Title (UZ)')),
                ('gallery_title_ru', models.TextField(blank=True, verbose_name='Gallery Title (RU)')),
                ('gallery_title_en', models.TextField(blank=True, verbose_name='Gallery Title (EN)')),
                ('contact_mini_title_uz', models.CharField(blank=True, max_length=255, verbose_name='Contact Mini Title (UZ)')),
                ('contact_mini_title_ru', models.CharField(blank=True, max_length=255, verbose_name='Contact Mini Title (RU)')),
                ('contact_mini_title_en', models.CharField(blank=True, max_length=255, verbose_name='Contact Mini Title (EN)')),
                ('contact_title_uz', models.TextField(blank=True, verbose_name='Contact Title (UZ)')),
                ('contact_title_ru', models.TextField(blank=True, verbose_name='Contact Title (RU)')),
                ('contact_title_en', models.TextField(blank=True, verbose_name='Contact Title (EN)')),
                ('contact_desc_uz', models.TextField(blank=True, verbose_name='Contact Desc (UZ)')),
                ('contact_desc_ru', models.TextField(blank=True, verbose_name='Contact Desc (RU)')),
                ('contact_desc_en', models.TextField(blank=True, verbose_name='Contact Desc (EN)')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
