# Generated by Django 6.0.4 on 2026-04-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='address_en',
            field=models.TextField(blank=True, verbose_name='Адрес (EN)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='address_ru',
            field=models.TextField(blank=True, verbose_name='Адрес (RU)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='address_uz',
            field=models.TextField(blank=True, verbose_name='Адрес (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Телефон'),
        ),
    ]
