# Generated by Django 6.0.4 on 2026-04-25 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesetting_address_en_sitesetting_address_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='tg_bot_token',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='tg_chat_id',
        ),
    ]
