# Generated by Django 4.2.30 on 2026-04-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_contactrequest_id_alter_emailaddress_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mini_title_uz', models.CharField(blank=True, max_length=255, verbose_name='Mini Title (UZ)')),
                ('mini_title_ru', models.CharField(blank=True, max_length=255, verbose_name='Mini Title (RU)')),
                ('mini_title_en', models.CharField(blank=True, max_length=255, verbose_name='Mini Title (EN)')),
                ('title_uz', models.TextField(blank=True, verbose_name='Title (UZ)')),
                ('title_ru', models.TextField(blank=True, verbose_name='Title (RU)')),
                ('title_en', models.TextField(blank=True, verbose_name='Title (EN)')),
                ('desc_uz', models.TextField(blank=True, verbose_name='Desc (UZ)')),
                ('desc_ru', models.TextField(blank=True, verbose_name='Desc (RU)')),
                ('desc_en', models.TextField(blank=True, verbose_name='Desc (EN)')),
            ],
            options={
                'verbose_name': 'Секция Contact',
                'verbose_name_plural': 'Секция Contact',
            },
        ),
        migrations.CreateModel(
            name='ExperienceSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mini_title_uz', models.CharField(blank=True, max_length=255, verbose_name='Mini Title (UZ)')),
                ('mini_title_ru', models.CharField(blank=True, max_length=255, verbose_name='Mini Title (RU)')),
                ('mini_title_en', models.CharField(blank=True, max_length=255, verbose_name='Mini Title (EN)')),
                ('title_uz', models.TextField(blank=True, verbose_name='Title (UZ)')),
                ('title_ru', models.TextField(blank=True, verbose_name='Title (RU)')),
                ('title_en', models.TextField(blank=True, verbose_name='Title (EN)')),
                ('desc_uz', models.TextField(blank=True, verbose_name='Desc (UZ)')),
                ('desc_ru', models.TextField(blank=True, verbose_name='Desc (RU)')),
                ('desc_en', models.TextField(blank=True, verbose_name='Desc (EN)')),
            ],
            options={
                'verbose_name': 'Секция Experience',
                'verbose_name_plural': 'Секция Experience',
            },
        ),
        migrations.CreateModel(
            name='GallerySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mini_title_uz', models.CharField(blank=True, max_length=255, verbose_name='Mini Title (UZ)')),
                ('mini_title_ru', models.CharField(blank=True, max_length=255, verbose_name='Mini Title (RU)')),
                ('mini_title_en', models.CharField(blank=True, max_length=255, verbose_name='Mini Title (EN)')),
                ('title_uz', models.TextField(blank=True, verbose_name='Title (UZ)')),
                ('title_ru', models.TextField(blank=True, verbose_name='Title (RU)')),
                ('title_en', models.TextField(blank=True, verbose_name='Title (EN)')),
            ],
            options={
                'verbose_name': 'Секция Gallery',
                'verbose_name_plural': 'Секция Gallery',
            },
        ),
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Логотип Navbar')),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Логотип Footer')),
            ],
            options={
                'verbose_name': 'Общие настройки',
                'verbose_name_plural': 'Общие настройки',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mini_title_uz', models.CharField(blank=True, max_length=255, verbose_name='Mini Title (UZ)')),
                ('mini_title_ru', models.CharField(blank=True, max_length=255, verbose_name='Mini Title (RU)')),
                ('mini_title_en', models.CharField(blank=True, max_length=255, verbose_name='Mini Title (EN)')),
                ('title_uz', models.TextField(blank=True, verbose_name='Title (UZ)')),
                ('title_ru', models.TextField(blank=True, verbose_name='Title (RU)')),
                ('title_en', models.TextField(blank=True, verbose_name='Title (EN)')),
                ('desc_uz', models.TextField(blank=True, verbose_name='Desc (UZ)')),
                ('desc_ru', models.TextField(blank=True, verbose_name='Desc (RU)')),
                ('desc_en', models.TextField(blank=True, verbose_name='Desc (EN)')),
            ],
            options={
                'verbose_name': 'Секция Hero',
                'verbose_name_plural': 'Секция Hero',
            },
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mini_title_uz', models.CharField(blank=True, max_length=255, verbose_name='Mini Title (UZ)')),
                ('mini_title_ru', models.CharField(blank=True, max_length=255, verbose_name='Mini Title (RU)')),
                ('mini_title_en', models.CharField(blank=True, max_length=255, verbose_name='Mini Title (EN)')),
                ('title_uz', models.TextField(blank=True, verbose_name='Title (UZ)')),
                ('title_ru', models.TextField(blank=True, verbose_name='Title (RU)')),
                ('title_en', models.TextField(blank=True, verbose_name='Title (EN)')),
                ('desc_uz', models.TextField(blank=True, verbose_name='Desc (UZ)')),
                ('desc_ru', models.TextField(blank=True, verbose_name='Desc (RU)')),
                ('desc_en', models.TextField(blank=True, verbose_name='Desc (EN)')),
            ],
            options={
                'verbose_name': 'Секция Services',
                'verbose_name_plural': 'Секция Services',
            },
        ),
        migrations.DeleteModel(
            name='SiteSetting',
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='experiencecard',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
