# Generated by Django 4.2.30 on 2026-04-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_generalsetting_brand_name_alter_contactrequest_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='hero_bg',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Фон Hero (Image)'),
        ),
    ]
