# Generated by Django 6.0.4 on 2026-05-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_herosection_hero_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecard',
            name='features_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Виды работ (RU) [каждый с новой строки]'),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='features_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Виды работ (UZ) [каждый с новой строки]'),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='full_desc_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание (RU)'),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='full_desc_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание (UZ)'),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services_photos/', verbose_name='Фото услуги'),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug (URL)'),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='steps_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Этапы (RU) [каждый с новой строки]'),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='steps_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Этапы (UZ) [каждый с новой строки]'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contactsection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='experiencecard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='experiencesection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gallerysection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='desc_en',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание (EN)'),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='desc_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание (RU)'),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='desc_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание (UZ)'),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Иконки (например: lift, special, escalator, supervision)'),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (EN)'),
        ),
        migrations.AlterField(
            model_name='servicesection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
