# Generated by Django 6.0.4 on 2026-05-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_servicecard_features_ru_servicecard_features_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecard',
            name='features_en',
            field=models.TextField(blank=True, null=True, verbose_name='Виды работ (EN) [каждый с новой строки]'),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='full_desc_en',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание (EN)'),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='steps_en',
            field=models.TextField(blank=True, null=True, verbose_name='Этапы (EN) [каждый с новой строки]'),
        ),
    ]
